### ISSUE TITLE
Error: unable to automatically load instrument, deploy may failed

### ISSUE THREAD

**Issue by OneSpare** [liquidinstruments/pymoku#2]
Hi,

when i was using pymoku on my windows PC, i received an error:
`FileNotFoundError: [Errno 2] no such file or directory: 'C:\\Users\\...\pymoku\\data/mokudata-474.tar.gz'`

**Comment by kaotigger** [comment]
I have the same problem when I tried to run the example code. I am using windows 10 and jupyter notebook.
After I put the code in /pymoku-master/pymoku folder instead of /pymoku-master folder, the error has disappear. And the code successfully runs.

**Comment by cogsy23** [comment]
Hi @OneSpare, @kaotigger.  Sorry for the slow response.

Make sure your pymoku install is up to date, and that you've fetch a copy of the instrument binaries:

```
pip install --upgrade pymoku
moku update fetch
```
