### ISSUE TITLE
Pymoku firmware requirements not compatible with iPad firmware requirments

### ISSUE THREAD

**Issue by awade** [liquidinstruments/pymoku#4]
Hi, I've been trying out the pymoku interface.  I have a simple test script for connecting to device on our network:

```python
from pymoku import Moku
from pymoku.instruments import LaserLockBox 

MokuHumanName = 'Space-White'

m = Moku.get_by_name(MokuHumanName)


i = m.deploy_or_connect(LaserLockBox)

m.close()
```

I get the following response
``` bash
>python testMoku.py Traceback (most recent call last):
  File "testMoku.py", line 6, in <module>
    m = Moku.get_by_name(MokuHumanName)
  File "/Users/awade/miniconda3/envs/pyenv3/lib/python3.7/site-packages/pymoku/__init__.py", line 284, in get_by_name
    return Moku(mokus[0], force=force, *args, **kwargs)
  File "/Users/awade/miniconda3/envs/pyenv3/lib/python3.7/site-packages/pymoku/__init__.py", line 154, in __init__
    .format(self.get_firmware_build(), PYMOKU_VERSION, self.get_ip()))
pymoku.MokuException: Moku:Lab firmware 511 incompatible with Pymoku v2.8.0. Please update using
 moku update fetch
 moku --ip=192.168.30.196 update install
```

I followed the instructions for updating via the command line.  When I run 'moku update fetch' it says latest is 511 and up to date and the install of whatever it has works fine:

```bash
> moku update fetch
PyMoku 2.8.0
mokudata-511-0.tar.gz Already up to date

> moku --ip=192.168.30.196 update install
PyMoku 2.8.0
Updating Moku 000753 from 511 to 511...
Firmware already up to date.
Checking for updates.
Applying updates...
Successfully applied updates. Your Moku:Lab will now shut down to complete the update process.
```
When I run my python script at the top of this issue it now connects successfully. 

However, now when I go to the iPad interface it comes up with a exclamation mark and refuses me access to the instrument until I update firmware from the iPad.  So I can't get python and iPad talking to Moku with same firmware version.  Is there a fix for this?

**Comment by cogsy23** [comment]
Hey @awade, sorry we didn't see this sooner...
This issue here is your pymoku version.  You can update with pip using
`pip install --upgrade pymoku`
2.8.1 is the current version.

**Comment by awade** [comment]
@cogsy23 Thank you, this seems to have resolved the issue.  I'm working from a conda install of python.  Maybe I just got an outdated version packaged with it.  Problem seems to be resolved now.

**Comment by awade** [comment]
Thanks for following up on my git issue.  This resolves my problem.  Thanks.

In another unrelated problem.  I'm trying to configure the PID filter
parameters but have trouble setting values.  I basically want a saturation
limited integrator initially and will later change to strait integrator at
a later time. I.e. no P or D terms.  However, it seems to be impossible to
define a set_pid_by_freq or set_pid_by_gain that gives me just
integrator terms.  It always seems to have some differentiator terms and
proportional terms.  Also the set crossover frequency doesn't seem to
correspond to defined values.

I can configure this in the iPad interface easily by unselecting everything
but the integrator terms.

What python command do I need to configure the PID block to get an
integrator with 0dB crossing at 1.5 kHz and saturation at 60 dB?

Cheers,
Andrew

Andrew Wade | *+6145 585 8014* (Mobile) |
andrew.richard.wade@gmail.com (Personal)
| andrew.wade@anu.edu.au (W)
